version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/rails
      - .env/development/database
    environment:
      - WEBPACKER_DEV_SERVER_HOST=wds

  wds:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/usr/src/app
    ports:
      - '3035:3035'
    env_file:
      - .env/development/rails
      - .env/development/database
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  redis:
    image: redis

  db:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
