default: &default
  adapter: postgresql
  encoding: ​unicode
  host:  <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>

development:
  <<: *default

test:
  <<: *default
  database: ​myapp_test​

production:
  <<: *default
